DROP TABLE IF EXISTS staff;

CREATE TABLE staff (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    full_name VARCHAR(255) NOT NULL,
    sex CHAR(1) DEFAULT NULL,
    nik VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS presences;

CREATE TABLE presences (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    presence_date DATE NOT NULL,
    in_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    out_time TIMESTAMP DEFAULT NULL,
    staff_id INTEGER NOT NULL, 
    FOREIGN KEY(staff_id)
        REFERENCES staff(id)
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    table_id INTEGER NOT NULL,
    table_name VARCHAR(255) DEFAULT 'staff',
    email VARCHAR(255) NOT NULL UNIQUE,
    pwd VARCHAR(255) NOT NULL,
    is_active CHAR(1) NOT NULL DEFAULT '1',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);